// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spawnset.proto

#ifndef PROTOBUF_spawnset_2eproto__INCLUDED
#define PROTOBUF_spawnset_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ew {
namespace spawner {
class PostSegment;
class PostSegmentDefaultTypeInternal;
extern PostSegmentDefaultTypeInternal _PostSegment_default_instance_;
class PreSegment;
class PreSegmentDefaultTypeInternal;
extern PreSegmentDefaultTypeInternal _PreSegment_default_instance_;
class RegionGraphEntry;
class RegionGraphEntryDefaultTypeInternal;
extern RegionGraphEntryDefaultTypeInternal _RegionGraphEntry_default_instance_;
class SpawnMapEntry;
class SpawnMapEntryDefaultTypeInternal;
extern SpawnMapEntryDefaultTypeInternal _SpawnMapEntry_default_instance_;
class SpawnTable;
class SpawnTableDefaultTypeInternal;
extern SpawnTableDefaultTypeInternal _SpawnTable_default_instance_;
}  // namespace spawner
}  // namespace ew

namespace ew {
namespace spawner {

namespace protobuf_spawnset_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_spawnset_2eproto

// ===================================================================

class PreSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.PreSegment) */ {
 public:
  PreSegment();
  virtual ~PreSegment();

  PreSegment(const PreSegment& from);

  inline PreSegment& operator=(const PreSegment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PreSegment& default_instance();

  static inline const PreSegment* internal_default_instance() {
    return reinterpret_cast<const PreSegment*>(
               &_PreSegment_default_instance_);
  }

  void Swap(PreSegment* other);

  // implements Message ----------------------------------------------

  inline PreSegment* New() const PROTOBUF_FINAL { return New(NULL); }

  PreSegment* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PreSegment& from);
  void MergeFrom(const PreSegment& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PreSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 intersectionSize = 2;
  void clear_intersectionsize();
  static const int kIntersectionSizeFieldNumber = 2;
  ::google::protobuf::uint32 intersectionsize() const;
  void set_intersectionsize(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ew.spawner.PreSegment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 intersectionsize_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PostSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.PostSegment) */ {
 public:
  PostSegment();
  virtual ~PostSegment();

  PostSegment(const PostSegment& from);

  inline PostSegment& operator=(const PostSegment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PostSegment& default_instance();

  static inline const PostSegment* internal_default_instance() {
    return reinterpret_cast<const PostSegment*>(
               &_PostSegment_default_instance_);
  }

  void Swap(PostSegment* other);

  // implements Message ----------------------------------------------

  inline PostSegment* New() const PROTOBUF_FINAL { return New(NULL); }

  PostSegment* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PostSegment& from);
  void MergeFrom(const PostSegment& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PostSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ew.spawner.PreSegment preSideSupports = 1;
  int presidesupports_size() const;
  void clear_presidesupports();
  static const int kPreSideSupportsFieldNumber = 1;
  const ::ew::spawner::PreSegment& presidesupports(int index) const;
  ::ew::spawner::PreSegment* mutable_presidesupports(int index);
  ::ew::spawner::PreSegment* add_presidesupports();
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::PreSegment >*
      mutable_presidesupports();
  const ::google::protobuf::RepeatedPtrField< ::ew::spawner::PreSegment >&
      presidesupports() const;

  // uint32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 overlapSize = 3;
  void clear_overlapsize();
  static const int kOverlapSizeFieldNumber = 3;
  ::google::protobuf::uint32 overlapsize() const;
  void set_overlapsize(::google::protobuf::uint32 value);

  // bool canSpawn = 4;
  void clear_canspawn();
  static const int kCanSpawnFieldNumber = 4;
  bool canspawn() const;
  void set_canspawn(bool value);

  // @@protoc_insertion_point(class_scope:ew.spawner.PostSegment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::PreSegment > presidesupports_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 overlapsize_;
  bool canspawn_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SpawnMapEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.SpawnMapEntry) */ {
 public:
  SpawnMapEntry();
  virtual ~SpawnMapEntry();

  SpawnMapEntry(const SpawnMapEntry& from);

  inline SpawnMapEntry& operator=(const SpawnMapEntry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnMapEntry& default_instance();

  static inline const SpawnMapEntry* internal_default_instance() {
    return reinterpret_cast<const SpawnMapEntry*>(
               &_SpawnMapEntry_default_instance_);
  }

  void Swap(SpawnMapEntry* other);

  // implements Message ----------------------------------------------

  inline SpawnMapEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnMapEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnMapEntry& from);
  void MergeFrom(const SpawnMapEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnMapEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ew.spawner.PostSegment postSideCounterparts = 1;
  int postsidecounterparts_size() const;
  void clear_postsidecounterparts();
  static const int kPostSideCounterpartsFieldNumber = 1;
  const ::ew::spawner::PostSegment& postsidecounterparts(int index) const;
  ::ew::spawner::PostSegment* mutable_postsidecounterparts(int index);
  ::ew::spawner::PostSegment* add_postsidecounterparts();
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >*
      mutable_postsidecounterparts();
  const ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >&
      postsidecounterparts() const;

  // @@protoc_insertion_point(class_scope:ew.spawner.SpawnMapEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment > postsidecounterparts_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RegionGraphEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.RegionGraphEntry) */ {
 public:
  RegionGraphEntry();
  virtual ~RegionGraphEntry();

  RegionGraphEntry(const RegionGraphEntry& from);

  inline RegionGraphEntry& operator=(const RegionGraphEntry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegionGraphEntry& default_instance();

  static inline const RegionGraphEntry* internal_default_instance() {
    return reinterpret_cast<const RegionGraphEntry*>(
               &_RegionGraphEntry_default_instance_);
  }

  void Swap(RegionGraphEntry* other);

  // implements Message ----------------------------------------------

  inline RegionGraphEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  RegionGraphEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RegionGraphEntry& from);
  void MergeFrom(const RegionGraphEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RegionGraphEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ew.spawner.PostSegment postSideNeighbors = 1;
  int postsideneighbors_size() const;
  void clear_postsideneighbors();
  static const int kPostSideNeighborsFieldNumber = 1;
  const ::ew::spawner::PostSegment& postsideneighbors(int index) const;
  ::ew::spawner::PostSegment* mutable_postsideneighbors(int index);
  ::ew::spawner::PostSegment* add_postsideneighbors();
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >*
      mutable_postsideneighbors();
  const ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >&
      postsideneighbors() const;

  // @@protoc_insertion_point(class_scope:ew.spawner.RegionGraphEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment > postsideneighbors_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------


// -------------------------------------------------------------------

class SpawnTable : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.SpawnTable) */ {
 public:
  SpawnTable();
  virtual ~SpawnTable();

  SpawnTable(const SpawnTable& from);

  inline SpawnTable& operator=(const SpawnTable& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnTable& default_instance();

  static inline const SpawnTable* internal_default_instance() {
    return reinterpret_cast<const SpawnTable*>(
               &_SpawnTable_default_instance_);
  }

  void Swap(SpawnTable* other);

  // implements Message ----------------------------------------------

  inline SpawnTable* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnTable* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnTable& from);
  void MergeFrom(const SpawnTable& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, .ew.spawner.SpawnMapEntry> preSpawnMap = 1;
  int prespawnmap_size() const;
  void clear_prespawnmap();
  static const int kPreSpawnMapFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnMapEntry >&
      prespawnmap() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnMapEntry >*
      mutable_prespawnmap();

  // map<uint32, .ew.spawner.RegionGraphEntry> postRegionGraph = 2;
  int postregiongraph_size() const;
  void clear_postregiongraph();
  static const int kPostRegionGraphFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::RegionGraphEntry >&
      postregiongraph() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::RegionGraphEntry >*
      mutable_postregiongraph();

  // uint32 version = 3;
  void clear_version();
  static const int kVersionFieldNumber = 3;
  ::google::protobuf::uint32 version() const;
  void set_version(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ew.spawner.SpawnTable)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::uint32, ::ew::spawner::SpawnMapEntry,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      SpawnTable_PreSpawnMapEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::uint32, ::ew::spawner::SpawnMapEntry,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > prespawnmap_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::uint32, ::ew::spawner::RegionGraphEntry,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      SpawnTable_PostRegionGraphEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::uint32, ::ew::spawner::RegionGraphEntry,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > postregiongraph_;
  ::google::protobuf::uint32 version_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PreSegment

// uint32 id = 1;
inline void PreSegment::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 PreSegment::id() const {
  // @@protoc_insertion_point(field_get:ew.spawner.PreSegment.id)
  return id_;
}
inline void PreSegment::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.PreSegment.id)
}

// uint32 intersectionSize = 2;
inline void PreSegment::clear_intersectionsize() {
  intersectionsize_ = 0u;
}
inline ::google::protobuf::uint32 PreSegment::intersectionsize() const {
  // @@protoc_insertion_point(field_get:ew.spawner.PreSegment.intersectionSize)
  return intersectionsize_;
}
inline void PreSegment::set_intersectionsize(::google::protobuf::uint32 value) {
  
  intersectionsize_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.PreSegment.intersectionSize)
}

// -------------------------------------------------------------------

// PostSegment

// repeated .ew.spawner.PreSegment preSideSupports = 1;
inline int PostSegment::presidesupports_size() const {
  return presidesupports_.size();
}
inline void PostSegment::clear_presidesupports() {
  presidesupports_.Clear();
}
inline const ::ew::spawner::PreSegment& PostSegment::presidesupports(int index) const {
  // @@protoc_insertion_point(field_get:ew.spawner.PostSegment.preSideSupports)
  return presidesupports_.Get(index);
}
inline ::ew::spawner::PreSegment* PostSegment::mutable_presidesupports(int index) {
  // @@protoc_insertion_point(field_mutable:ew.spawner.PostSegment.preSideSupports)
  return presidesupports_.Mutable(index);
}
inline ::ew::spawner::PreSegment* PostSegment::add_presidesupports() {
  // @@protoc_insertion_point(field_add:ew.spawner.PostSegment.preSideSupports)
  return presidesupports_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ew::spawner::PreSegment >*
PostSegment::mutable_presidesupports() {
  // @@protoc_insertion_point(field_mutable_list:ew.spawner.PostSegment.preSideSupports)
  return &presidesupports_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ew::spawner::PreSegment >&
PostSegment::presidesupports() const {
  // @@protoc_insertion_point(field_list:ew.spawner.PostSegment.preSideSupports)
  return presidesupports_;
}

// uint32 id = 2;
inline void PostSegment::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 PostSegment::id() const {
  // @@protoc_insertion_point(field_get:ew.spawner.PostSegment.id)
  return id_;
}
inline void PostSegment::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.PostSegment.id)
}

// uint32 overlapSize = 3;
inline void PostSegment::clear_overlapsize() {
  overlapsize_ = 0u;
}
inline ::google::protobuf::uint32 PostSegment::overlapsize() const {
  // @@protoc_insertion_point(field_get:ew.spawner.PostSegment.overlapSize)
  return overlapsize_;
}
inline void PostSegment::set_overlapsize(::google::protobuf::uint32 value) {
  
  overlapsize_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.PostSegment.overlapSize)
}

// bool canSpawn = 4;
inline void PostSegment::clear_canspawn() {
  canspawn_ = false;
}
inline bool PostSegment::canspawn() const {
  // @@protoc_insertion_point(field_get:ew.spawner.PostSegment.canSpawn)
  return canspawn_;
}
inline void PostSegment::set_canspawn(bool value) {
  
  canspawn_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.PostSegment.canSpawn)
}

// -------------------------------------------------------------------

// SpawnMapEntry

// repeated .ew.spawner.PostSegment postSideCounterparts = 1;
inline int SpawnMapEntry::postsidecounterparts_size() const {
  return postsidecounterparts_.size();
}
inline void SpawnMapEntry::clear_postsidecounterparts() {
  postsidecounterparts_.Clear();
}
inline const ::ew::spawner::PostSegment& SpawnMapEntry::postsidecounterparts(int index) const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnMapEntry.postSideCounterparts)
  return postsidecounterparts_.Get(index);
}
inline ::ew::spawner::PostSegment* SpawnMapEntry::mutable_postsidecounterparts(int index) {
  // @@protoc_insertion_point(field_mutable:ew.spawner.SpawnMapEntry.postSideCounterparts)
  return postsidecounterparts_.Mutable(index);
}
inline ::ew::spawner::PostSegment* SpawnMapEntry::add_postsidecounterparts() {
  // @@protoc_insertion_point(field_add:ew.spawner.SpawnMapEntry.postSideCounterparts)
  return postsidecounterparts_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >*
SpawnMapEntry::mutable_postsidecounterparts() {
  // @@protoc_insertion_point(field_mutable_list:ew.spawner.SpawnMapEntry.postSideCounterparts)
  return &postsidecounterparts_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >&
SpawnMapEntry::postsidecounterparts() const {
  // @@protoc_insertion_point(field_list:ew.spawner.SpawnMapEntry.postSideCounterparts)
  return postsidecounterparts_;
}

// -------------------------------------------------------------------

// RegionGraphEntry

// repeated .ew.spawner.PostSegment postSideNeighbors = 1;
inline int RegionGraphEntry::postsideneighbors_size() const {
  return postsideneighbors_.size();
}
inline void RegionGraphEntry::clear_postsideneighbors() {
  postsideneighbors_.Clear();
}
inline const ::ew::spawner::PostSegment& RegionGraphEntry::postsideneighbors(int index) const {
  // @@protoc_insertion_point(field_get:ew.spawner.RegionGraphEntry.postSideNeighbors)
  return postsideneighbors_.Get(index);
}
inline ::ew::spawner::PostSegment* RegionGraphEntry::mutable_postsideneighbors(int index) {
  // @@protoc_insertion_point(field_mutable:ew.spawner.RegionGraphEntry.postSideNeighbors)
  return postsideneighbors_.Mutable(index);
}
inline ::ew::spawner::PostSegment* RegionGraphEntry::add_postsideneighbors() {
  // @@protoc_insertion_point(field_add:ew.spawner.RegionGraphEntry.postSideNeighbors)
  return postsideneighbors_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >*
RegionGraphEntry::mutable_postsideneighbors() {
  // @@protoc_insertion_point(field_mutable_list:ew.spawner.RegionGraphEntry.postSideNeighbors)
  return &postsideneighbors_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ew::spawner::PostSegment >&
RegionGraphEntry::postsideneighbors() const {
  // @@protoc_insertion_point(field_list:ew.spawner.RegionGraphEntry.postSideNeighbors)
  return postsideneighbors_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SpawnTable

// map<uint32, .ew.spawner.SpawnMapEntry> preSpawnMap = 1;
inline int SpawnTable::prespawnmap_size() const {
  return prespawnmap_.size();
}
inline void SpawnTable::clear_prespawnmap() {
  prespawnmap_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnMapEntry >&
SpawnTable::prespawnmap() const {
  // @@protoc_insertion_point(field_map:ew.spawner.SpawnTable.preSpawnMap)
  return prespawnmap_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnMapEntry >*
SpawnTable::mutable_prespawnmap() {
  // @@protoc_insertion_point(field_mutable_map:ew.spawner.SpawnTable.preSpawnMap)
  return prespawnmap_.MutableMap();
}

// map<uint32, .ew.spawner.RegionGraphEntry> postRegionGraph = 2;
inline int SpawnTable::postregiongraph_size() const {
  return postregiongraph_.size();
}
inline void SpawnTable::clear_postregiongraph() {
  postregiongraph_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::RegionGraphEntry >&
SpawnTable::postregiongraph() const {
  // @@protoc_insertion_point(field_map:ew.spawner.SpawnTable.postRegionGraph)
  return postregiongraph_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::RegionGraphEntry >*
SpawnTable::mutable_postregiongraph() {
  // @@protoc_insertion_point(field_mutable_map:ew.spawner.SpawnTable.postRegionGraph)
  return postregiongraph_.MutableMap();
}

// uint32 version = 3;
inline void SpawnTable::clear_version() {
  version_ = 0u;
}
inline ::google::protobuf::uint32 SpawnTable::version() const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnTable.version)
  return version_;
}
inline void SpawnTable::set_version(::google::protobuf::uint32 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.SpawnTable.version)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace spawner
}  // namespace ew

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_spawnset_2eproto__INCLUDED
