// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spawnset.proto

#ifndef PROTOBUF_spawnset_2eproto__INCLUDED
#define PROTOBUF_spawnset_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ew {
namespace spawner {
class SpawnEntry;
class SpawnEntryDefaultTypeInternal;
extern SpawnEntryDefaultTypeInternal _SpawnEntry_default_instance_;
class SpawnEntry_PostSegment;
class SpawnEntry_PostSegmentDefaultTypeInternal;
extern SpawnEntry_PostSegmentDefaultTypeInternal _SpawnEntry_PostSegment_default_instance_;
class SpawnEntry_PreSegment;
class SpawnEntry_PreSegmentDefaultTypeInternal;
extern SpawnEntry_PreSegmentDefaultTypeInternal _SpawnEntry_PreSegment_default_instance_;
class SpawnTable;
class SpawnTableDefaultTypeInternal;
extern SpawnTableDefaultTypeInternal _SpawnTable_default_instance_;
}  // namespace spawner
}  // namespace ew

namespace ew {
namespace spawner {

namespace protobuf_spawnset_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_spawnset_2eproto

// ===================================================================

class SpawnEntry_PreSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.SpawnEntry.PreSegment) */ {
 public:
  SpawnEntry_PreSegment();
  virtual ~SpawnEntry_PreSegment();

  SpawnEntry_PreSegment(const SpawnEntry_PreSegment& from);

  inline SpawnEntry_PreSegment& operator=(const SpawnEntry_PreSegment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnEntry_PreSegment& default_instance();

  static inline const SpawnEntry_PreSegment* internal_default_instance() {
    return reinterpret_cast<const SpawnEntry_PreSegment*>(
               &_SpawnEntry_PreSegment_default_instance_);
  }

  void Swap(SpawnEntry_PreSegment* other);

  // implements Message ----------------------------------------------

  inline SpawnEntry_PreSegment* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnEntry_PreSegment* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnEntry_PreSegment& from);
  void MergeFrom(const SpawnEntry_PreSegment& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnEntry_PreSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 intersectionSize = 2;
  void clear_intersectionsize();
  static const int kIntersectionSizeFieldNumber = 2;
  ::google::protobuf::uint32 intersectionsize() const;
  void set_intersectionsize(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ew.spawner.SpawnEntry.PreSegment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 intersectionsize_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SpawnEntry_PostSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.SpawnEntry.PostSegment) */ {
 public:
  SpawnEntry_PostSegment();
  virtual ~SpawnEntry_PostSegment();

  SpawnEntry_PostSegment(const SpawnEntry_PostSegment& from);

  inline SpawnEntry_PostSegment& operator=(const SpawnEntry_PostSegment& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnEntry_PostSegment& default_instance();

  static inline const SpawnEntry_PostSegment* internal_default_instance() {
    return reinterpret_cast<const SpawnEntry_PostSegment*>(
               &_SpawnEntry_PostSegment_default_instance_);
  }

  void Swap(SpawnEntry_PostSegment* other);

  // implements Message ----------------------------------------------

  inline SpawnEntry_PostSegment* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnEntry_PostSegment* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnEntry_PostSegment& from);
  void MergeFrom(const SpawnEntry_PostSegment& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnEntry_PostSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ew.spawner.SpawnEntry.PreSegment preSideSupports = 1;
  int presidesupports_size() const;
  void clear_presidesupports();
  static const int kPreSideSupportsFieldNumber = 1;
  const ::ew::spawner::SpawnEntry_PreSegment& presidesupports(int index) const;
  ::ew::spawner::SpawnEntry_PreSegment* mutable_presidesupports(int index);
  ::ew::spawner::SpawnEntry_PreSegment* add_presidesupports();
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >*
      mutable_presidesupports();
  const ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >&
      presidesupports() const;

  // uint32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 overlapSize = 3;
  void clear_overlapsize();
  static const int kOverlapSizeFieldNumber = 3;
  ::google::protobuf::uint32 overlapsize() const;
  void set_overlapsize(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ew.spawner.SpawnEntry.PostSegment)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment > presidesupports_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 overlapsize_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SpawnEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.SpawnEntry) */ {
 public:
  SpawnEntry();
  virtual ~SpawnEntry();

  SpawnEntry(const SpawnEntry& from);

  inline SpawnEntry& operator=(const SpawnEntry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnEntry& default_instance();

  static inline const SpawnEntry* internal_default_instance() {
    return reinterpret_cast<const SpawnEntry*>(
               &_SpawnEntry_default_instance_);
  }

  void Swap(SpawnEntry* other);

  // implements Message ----------------------------------------------

  inline SpawnEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnEntry& from);
  void MergeFrom(const SpawnEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SpawnEntry_PreSegment PreSegment;
  typedef SpawnEntry_PostSegment PostSegment;

  // accessors -------------------------------------------------------

  // repeated .ew.spawner.SpawnEntry.PostSegment postSideCounterparts = 1;
  int postsidecounterparts_size() const;
  void clear_postsidecounterparts();
  static const int kPostSideCounterpartsFieldNumber = 1;
  const ::ew::spawner::SpawnEntry_PostSegment& postsidecounterparts(int index) const;
  ::ew::spawner::SpawnEntry_PostSegment* mutable_postsidecounterparts(int index);
  ::ew::spawner::SpawnEntry_PostSegment* add_postsidecounterparts();
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PostSegment >*
      mutable_postsidecounterparts();
  const ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PostSegment >&
      postsidecounterparts() const;

  // repeated .ew.spawner.SpawnEntry.PreSegment preSideNeighbors = 2;
  int presideneighbors_size() const;
  void clear_presideneighbors();
  static const int kPreSideNeighborsFieldNumber = 2;
  const ::ew::spawner::SpawnEntry_PreSegment& presideneighbors(int index) const;
  ::ew::spawner::SpawnEntry_PreSegment* mutable_presideneighbors(int index);
  ::ew::spawner::SpawnEntry_PreSegment* add_presideneighbors();
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >*
      mutable_presideneighbors();
  const ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >&
      presideneighbors() const;

  // bool canSpawn = 3;
  void clear_canspawn();
  static const int kCanSpawnFieldNumber = 3;
  bool canspawn() const;
  void set_canspawn(bool value);

  // @@protoc_insertion_point(class_scope:ew.spawner.SpawnEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PostSegment > postsidecounterparts_;
  ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment > presideneighbors_;
  bool canspawn_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class SpawnTable : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ew.spawner.SpawnTable) */ {
 public:
  SpawnTable();
  virtual ~SpawnTable();

  SpawnTable(const SpawnTable& from);

  inline SpawnTable& operator=(const SpawnTable& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpawnTable& default_instance();

  static inline const SpawnTable* internal_default_instance() {
    return reinterpret_cast<const SpawnTable*>(
               &_SpawnTable_default_instance_);
  }

  void Swap(SpawnTable* other);

  // implements Message ----------------------------------------------

  inline SpawnTable* New() const PROTOBUF_FINAL { return New(NULL); }

  SpawnTable* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SpawnTable& from);
  void MergeFrom(const SpawnTable& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SpawnTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, .ew.spawner.SpawnEntry> entries = 1;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnEntry >&
      entries() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnEntry >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:ew.spawner.SpawnTable)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::uint32, ::ew::spawner::SpawnEntry,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      SpawnTable_EntriesEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::uint32, ::ew::spawner::SpawnEntry,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > entries_;
  mutable int _cached_size_;
  friend struct protobuf_spawnset_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SpawnEntry_PreSegment

// uint32 id = 1;
inline void SpawnEntry_PreSegment::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEntry_PreSegment::id() const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.PreSegment.id)
  return id_;
}
inline void SpawnEntry_PreSegment::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.SpawnEntry.PreSegment.id)
}

// uint32 intersectionSize = 2;
inline void SpawnEntry_PreSegment::clear_intersectionsize() {
  intersectionsize_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEntry_PreSegment::intersectionsize() const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.PreSegment.intersectionSize)
  return intersectionsize_;
}
inline void SpawnEntry_PreSegment::set_intersectionsize(::google::protobuf::uint32 value) {
  
  intersectionsize_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.SpawnEntry.PreSegment.intersectionSize)
}

// -------------------------------------------------------------------

// SpawnEntry_PostSegment

// repeated .ew.spawner.SpawnEntry.PreSegment preSideSupports = 1;
inline int SpawnEntry_PostSegment::presidesupports_size() const {
  return presidesupports_.size();
}
inline void SpawnEntry_PostSegment::clear_presidesupports() {
  presidesupports_.Clear();
}
inline const ::ew::spawner::SpawnEntry_PreSegment& SpawnEntry_PostSegment::presidesupports(int index) const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.PostSegment.preSideSupports)
  return presidesupports_.Get(index);
}
inline ::ew::spawner::SpawnEntry_PreSegment* SpawnEntry_PostSegment::mutable_presidesupports(int index) {
  // @@protoc_insertion_point(field_mutable:ew.spawner.SpawnEntry.PostSegment.preSideSupports)
  return presidesupports_.Mutable(index);
}
inline ::ew::spawner::SpawnEntry_PreSegment* SpawnEntry_PostSegment::add_presidesupports() {
  // @@protoc_insertion_point(field_add:ew.spawner.SpawnEntry.PostSegment.preSideSupports)
  return presidesupports_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >*
SpawnEntry_PostSegment::mutable_presidesupports() {
  // @@protoc_insertion_point(field_mutable_list:ew.spawner.SpawnEntry.PostSegment.preSideSupports)
  return &presidesupports_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >&
SpawnEntry_PostSegment::presidesupports() const {
  // @@protoc_insertion_point(field_list:ew.spawner.SpawnEntry.PostSegment.preSideSupports)
  return presidesupports_;
}

// uint32 id = 2;
inline void SpawnEntry_PostSegment::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEntry_PostSegment::id() const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.PostSegment.id)
  return id_;
}
inline void SpawnEntry_PostSegment::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.SpawnEntry.PostSegment.id)
}

// uint32 overlapSize = 3;
inline void SpawnEntry_PostSegment::clear_overlapsize() {
  overlapsize_ = 0u;
}
inline ::google::protobuf::uint32 SpawnEntry_PostSegment::overlapsize() const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.PostSegment.overlapSize)
  return overlapsize_;
}
inline void SpawnEntry_PostSegment::set_overlapsize(::google::protobuf::uint32 value) {
  
  overlapsize_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.SpawnEntry.PostSegment.overlapSize)
}

// -------------------------------------------------------------------

// SpawnEntry

// repeated .ew.spawner.SpawnEntry.PostSegment postSideCounterparts = 1;
inline int SpawnEntry::postsidecounterparts_size() const {
  return postsidecounterparts_.size();
}
inline void SpawnEntry::clear_postsidecounterparts() {
  postsidecounterparts_.Clear();
}
inline const ::ew::spawner::SpawnEntry_PostSegment& SpawnEntry::postsidecounterparts(int index) const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.postSideCounterparts)
  return postsidecounterparts_.Get(index);
}
inline ::ew::spawner::SpawnEntry_PostSegment* SpawnEntry::mutable_postsidecounterparts(int index) {
  // @@protoc_insertion_point(field_mutable:ew.spawner.SpawnEntry.postSideCounterparts)
  return postsidecounterparts_.Mutable(index);
}
inline ::ew::spawner::SpawnEntry_PostSegment* SpawnEntry::add_postsidecounterparts() {
  // @@protoc_insertion_point(field_add:ew.spawner.SpawnEntry.postSideCounterparts)
  return postsidecounterparts_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PostSegment >*
SpawnEntry::mutable_postsidecounterparts() {
  // @@protoc_insertion_point(field_mutable_list:ew.spawner.SpawnEntry.postSideCounterparts)
  return &postsidecounterparts_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PostSegment >&
SpawnEntry::postsidecounterparts() const {
  // @@protoc_insertion_point(field_list:ew.spawner.SpawnEntry.postSideCounterparts)
  return postsidecounterparts_;
}

// repeated .ew.spawner.SpawnEntry.PreSegment preSideNeighbors = 2;
inline int SpawnEntry::presideneighbors_size() const {
  return presideneighbors_.size();
}
inline void SpawnEntry::clear_presideneighbors() {
  presideneighbors_.Clear();
}
inline const ::ew::spawner::SpawnEntry_PreSegment& SpawnEntry::presideneighbors(int index) const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.preSideNeighbors)
  return presideneighbors_.Get(index);
}
inline ::ew::spawner::SpawnEntry_PreSegment* SpawnEntry::mutable_presideneighbors(int index) {
  // @@protoc_insertion_point(field_mutable:ew.spawner.SpawnEntry.preSideNeighbors)
  return presideneighbors_.Mutable(index);
}
inline ::ew::spawner::SpawnEntry_PreSegment* SpawnEntry::add_presideneighbors() {
  // @@protoc_insertion_point(field_add:ew.spawner.SpawnEntry.preSideNeighbors)
  return presideneighbors_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >*
SpawnEntry::mutable_presideneighbors() {
  // @@protoc_insertion_point(field_mutable_list:ew.spawner.SpawnEntry.preSideNeighbors)
  return &presideneighbors_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ew::spawner::SpawnEntry_PreSegment >&
SpawnEntry::presideneighbors() const {
  // @@protoc_insertion_point(field_list:ew.spawner.SpawnEntry.preSideNeighbors)
  return presideneighbors_;
}

// bool canSpawn = 3;
inline void SpawnEntry::clear_canspawn() {
  canspawn_ = false;
}
inline bool SpawnEntry::canspawn() const {
  // @@protoc_insertion_point(field_get:ew.spawner.SpawnEntry.canSpawn)
  return canspawn_;
}
inline void SpawnEntry::set_canspawn(bool value) {
  
  canspawn_ = value;
  // @@protoc_insertion_point(field_set:ew.spawner.SpawnEntry.canSpawn)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SpawnTable

// map<uint32, .ew.spawner.SpawnEntry> entries = 1;
inline int SpawnTable::entries_size() const {
  return entries_.size();
}
inline void SpawnTable::clear_entries() {
  entries_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnEntry >&
SpawnTable::entries() const {
  // @@protoc_insertion_point(field_map:ew.spawner.SpawnTable.entries)
  return entries_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::ew::spawner::SpawnEntry >*
SpawnTable::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_map:ew.spawner.SpawnTable.entries)
  return entries_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace spawner
}  // namespace ew

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_spawnset_2eproto__INCLUDED
